In [1]:
import numpy as np
import random

In [2]:
A_Matrisi = [[random.randint(0, 10) for _ in range(3)] for _ in range(3)]

In [3]:
print(A_Matrisi)

[[4, 8, 2], [1, 3, 6], [2, 1, 8]]


In [4]:
B_Matrisi = [[random.randint(0, 10) for _ in range(3)] for _ in range(3)]

In [5]:
print(B_Matrisi)

[[2, 4, 0], [4, 8, 4], [1, 8, 6]]


In [6]:
def matrisOlustur(x,y):
    return [[random.randint(0, 10) for _ in range(y)] for _ in range(x)]

In [7]:
def birimMatrisOlusturucu(x):
    birimMatris = []
    for i in range(x):
        satir = []
        for j in range(x):
            if (i==j):
                satir.append(1)
            else:
                satir.append(0)
        birimMatris.append(satir)
    return birimMatris
                

In [8]:
print(birimMatrisOlusturucu(3))

[[1, 0, 0], [0, 1, 0], [0, 0, 1]]


In [9]:
def transpozeAl(matris):
    satir_sayisi = len(matris)
    sutun_sayisi = len(matris[0])
    
    transpozeMatris = []
    for i in range(sutun_sayisi):
        satir = []
        for j in range(satir_sayisi):
            satir.append(matris[j][i])
        transpozeMatris.append(satir)
    return transpozeMatris

In [10]:
print(transpozeAl(A_Matrisi))

[[4, 1, 2], [8, 3, 1], [2, 6, 8]]


In [11]:
def matrisCarpimi(matris1,matris2):
    satir1 = len(matris1)
    sutun1 = len(matris1[0])

    
    satir2 = len(matris2)
    sutun2 = len(matris2[0])



    sonucMatris = []

    if (sutun1 != satir2):

        return "satir sütun sayisi eşit değil carpim yapilamaz"
    
    else:
        for i in range(satir1):
            satir = []
            for k in range(sutun2):
                deger = 0
                for j in range (sutun1):
                    deger += matris1[i][j] * matris2[j][k]
                satir.append(deger)
            sonucMatris.append(satir)
    return sonucMatris
                        
    

In [12]:
x_matrisi = matrisOlustur(2,3)
y_matrisi = matrisOlustur(3,4)



print(x_matrisi)
print(y_matrisi)


[[7, 0, 0], [7, 5, 1]]
[[6, 10, 1, 5], [7, 7, 4, 6], [1, 2, 8, 1]]


In [13]:
print("satir sayisi",len(x_matrisi))
print("sutun sayisi",len(x_matrisi[0]))
print(transpozeAl(x_matrisi))

satir sayisi 2
sutun sayisi 3
[[7, 7], [0, 5], [0, 1]]


In [14]:
print(matrisCarpimi(x_matrisi,y_matrisi))

[[42, 70, 7, 35], [78, 107, 35, 66]]


In [15]:
k_matrisi = [[2,2],[2,2]]
l_matrisi = [[2,2],[2,2]]

if (k_matrisi == l_matrisi):
    print("eşit")
else:
    print("eşit değil")

eşit


In [16]:
def simetrikMatrisMi(matris):
    if (matris == transpozeAl(matris)):
        return 1
    else:
        return 0

In [17]:
simetrik_matris = [[1,0,2],[0,7,5],[2,5,1]]

In [18]:
simetrikMatrisMi(x_matrisi)

0

In [19]:
if(transpozeAl(matrisCarpimi(x_matrisi,y_matrisi)) == matrisCarpimi(transpozeAl(y_matrisi),transpozeAl(x_matrisi))):
    print("eşit")
else:
    print("eşit değil")

eşit


In [20]:
A = np.array(matrisOlustur(4,4))

In [21]:
b = np.array([1,6,3,8])

In [22]:
rank_A = np.linalg.matrix_rank(A)

In [23]:
print(rank_A)

4


In [24]:
birlestirilmisMatris = np.column_stack((A, b))
rank_birlesmis = np.linalg.matrix_rank(birlestirilmisMatris)

In [25]:
print(rank_birlesmis)

4


In [26]:
print(A)
print(np.linalg.matrix_transpose(A))

[[ 7  0  1 10]
 [10  5  9  3]
 [ 4  6  4  2]
 [10  8  9  9]]
[[ 7 10  4 10]
 [ 0  5  6  8]
 [ 1  9  4  9]
 [10  3  2  9]]


In [27]:
print(np.linalg.matrix_norm(A))

27.622454633866266
