In [1]:
import numpy as np

In [2]:
my_list = [10,20,30,40]

In [3]:
np.array(my_list)

array([10, 20, 30, 40])

In [4]:
my_numpy_array = np.array(my_list)

In [7]:
my_numpy_array.max()

np.int64(40)

In [9]:
np.ones(4)

array([1., 1., 1., 1.])

In [10]:
np.random.random(5)

array([0.92046286, 0.53476455, 0.52865556, 0.73469856, 0.85730587])

In [11]:
mylist1 = [1,2]

In [12]:
mylist2 = [2,3]

In [13]:
mylist1 + mylist2

[1, 2, 2, 3]

In [14]:
mnl1= np.array(mylist1)

In [15]:
mnl2 = np.array(mylist2)

In [17]:
mnl1 + mnl2

array([3, 5])

In [18]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
np_array = np.arange(0,20,2)

In [22]:
np_array[0]

np.int64(0)

In [23]:
np_array[-1]

np.int64(18)