In [1]:
import numpy as np

In [2]:
first_array = np.array([[10,20],[30,40]])
second_array = np.array([[1,2],[3,4]])

In [3]:
first_array + second_array

array([[11, 22],
       [33, 44]])

In [4]:
first_array * second_array

array([[ 10,  40],
       [ 90, 160]])

In [8]:
first_matrix = np.array([[10,20,30]])

In [10]:
first_matrix.shape

(1, 3)

In [11]:
second_matrix = np.array([[10],[20],[30]])

In [12]:
second_matrix.shape

(3, 1)

In [14]:
first_matrix.dot(second_matrix).shape

(1, 1)

In [15]:
new_array = np.random.randint(1,100,20)

In [16]:
new_array

array([96, 22, 27, 81, 60, 49, 89, 12, 62, 46, 46, 63, 21, 42, 42, 49, 61,
       62, 21, 31])

In [17]:
new_array > 25

array([ True, False,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True])

In [18]:
new_array[new_array > 25]

array([96, 27, 81, 60, 49, 89, 62, 46, 46, 63, 42, 42, 49, 61, 62, 31])

In [19]:
matrix_array = np.array([[10,20],[20,30],[30,40]])

In [20]:
matrix_array.transpose()

array([[10, 20, 30],
       [20, 30, 40]])

In [21]:
random_array = np.random.random((6,1))

In [22]:
random_array

array([[0.90034574],
       [0.28165599],
       [0.93478883],
       [0.87230467],
       [0.13228261],
       [0.36584084]])

In [23]:
random_array.reshape(2,3)

array([[0.90034574, 0.28165599, 0.93478883],
       [0.87230467, 0.13228261, 0.36584084]])

In [24]:
data = np.array([10,12,13,15,18,25,100,105])

In [25]:
mean = np.mean(data)

In [26]:
mean

np.float64(37.25)

In [27]:
data.sum() / len(data)

np.float64(37.25)

In [28]:
std = np.std(data)

In [29]:
std

np.float64(37.9333296719389)

In [30]:
z_scores = (data - mean) / std

In [31]:
z_scores

array([-0.71836562, -0.66564154, -0.6392795 , -0.58655542, -0.50746929,
       -0.322935  ,  1.65421809,  1.78602829])

In [32]:
z_scores[z_scores>1]

array([1.65421809, 1.78602829])