In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import(
accuracy_score,
precision_score,
recall_score,
f1_score,
confusion_matrix,
classification_report
)

In [2]:
from keras.models import Sequential
from keras.layers import Dense

In [3]:
veriseti = pd.read_csv("immuno.csv")

In [4]:
# Girdi ve hedef
X = veriseti.iloc[:, :-1].values
y = veriseti.iloc[:, -1].values

# Eğitim-test bölme
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.30, random_state=0, stratify=y
)

# Ölçekleme
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


In [7]:
X[:5]

array([[  1.  ,  22.  ,   2.25,  14.  ,   3.  ,  51.  ,  50.  ],
       [  1.  ,  15.  ,   3.  ,   2.  ,   3.  , 900.  ,  70.  ],
       [  2.  ,  28.  ,   7.5 ,   4.  ,   1.  ,   9.  ,   2.  ],
       [  2.  ,  19.  ,   6.  ,   2.  ,   1.  , 225.  ,   8.  ],
       [  2.  ,  32.  ,  12.  ,   6.  ,   3.  ,  35.  ,   5.  ]])

In [8]:
y[:5]

array([1, 1, 1, 1, 0])

In [9]:
model = Sequential()
model.add(Dense(8, kernel_initializer='uniform', activation='relu', input_dim=X_train.shape[1]))
model.add(Dense(8, kernel_initializer='uniform', activation='relu'))
model.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))


/opt/anaconda3/lib/python3.13/site-packages/keras/src/layers/core/dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [10]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Eğitim
model.fit(X_train, y_train, batch_size=10, epochs=150, verbose=0)

In [11]:
y_pred_prob = model.predict(X_test)
y_pred = (y_pred_prob > 0.5).astype(int)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step


array([[1],
       [1],
       [1],
       [1],
       [1]])

In [12]:
y_pred_prob[:5]


array([[0.78478384],
       [0.78505296],
       [0.8243439 ],
       [0.524431  ],
       [0.72901404]], dtype=float32)

In [13]:
y_pred[:5]


array([[1],
       [1],
       [1],
       [1],
       [1]])

In [16]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 0.7
Precision: 0.7
Recall: 1.0
F1 Score: 0.8235294117647058

Confusion Matrix:
[[ 0  6]
 [ 0 14]]

Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         6
           1       0.70      1.00      0.82        14

    accuracy                           0.70        20
   macro avg       0.35      0.50      0.41        20
weighted avg       0.49      0.70      0.58        20



/opt/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
